server:
  port: 8095

spring:
  application:
      name: shop-cart-api

eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://e0:8000/eureka/,http://e1:8001/eureka/,http://e2:8002/eureka/

sku:
  count:
    limit: 10